### PR TITLE
Update GitHub Actions tool versions and keep them consistent

### PR DESCRIPTION
**Pull request by paazmaya**
Replacing #208 to have cleaner history.

---

Well this keeps failing, most likely `postinstall` of prisma is not triggered or something, but I will look again once #206 is done.

### CODE REVIEW

**Comment by pashidlos** [comment]
you are right about postinstall
@paazmaya that is the issue with prisma generate https://github.com/Visual-Regression-Tracker/backend/actions/runs/5531274860/jobs/10091749742?pr=211#step:7:13

**Comment by paazmaya** [comment]
... and just when continuing upgrading to major version 4, they released five!
https://github.com/prisma/prisma/releases/tag/5.0.0

**Comment by pashidlos** [comment]
> ... and just when continuing upgrading to major version 4, they released five! https://github.com/prisma/prisma/releases/tag/5.0.0

I was quite overwhelmed when they released v3 with amount of breaking changes :D
cannot even imagine what it costs to jump straight to v5

**Comment by pashidlos** [comment]
@paazmaya some changes revealed old issue that I completely forgot https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/137
It seams we are limited with Node `14`

that revealed the gap I used to check manually after docker images are build so I added acceptance step to test docker image is build and containers are up and running

**Comment by paazmaya** [comment]
Lets see if downgrading Ubuntu will make the difference.

I dont want to downgrade Node.js as I like to follow https://github.com/nodejs/release#release-schedule so that the "maintenance" version is the lowest.
Having said that, 16 is only in "maintenance" state for few more months.
Dropping Node.js versions tends to be a major change...

**Comment by paazmaya** [comment]
Looks like Ubuntu version was the case for unit tests failing due to missing Prisma postinstall, now CI is failing later...

**Comment by pashidlos** [comment]
> Looks like Ubuntu version was the case for unit tests failing due to missing Prisma postinstall, now CI is failing later... and it does seem to be the same issue as in [Visual-Regression-Tracker/Visual-Regression-Tracker#137](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/137)
> 
> ```
> Run npx ts-node ./prisma/manual_migrations.ts
>   npx ts-node ./prisma/manual_migrations.ts
>   shell: /usr/bin/bash -e {0}
>   env:
>     ORGANIZATION_PROVIDER: gh
>     OWNER_NAME: Visual-Regression-Tracker
>     REPOSITORY_NAME: backend
> (node:2986) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> node[2986]: ../src/node_http_parser.cc:543:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
>  1: 0xb090e0 node::Abort() [node]
>  2: 0xb0915e  [node]
>  3: 0xb21de2  [node]
>  4: 0xd3df8e  [node]
>  5: 0xd3f3af v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
>  6: 0x15d9f39  [node]
> Aborted (core dumped)
> Error: Process completed with exit code 134.
> ```
> 
> How about getting #206 thru first and then see if this problem repeats or gets fixed?

I think we could make it working at least with note 14 together with acceptance tests for docker images 
that will make it easier to check if everything is working fine

**Pull request merged**
