### PR TITLE
Prisma upgrade

### PR DESCRIPTION
**Pull request by paazmaya**
#200 lets see how to get this started...

So far just upgraded to v3 and formatted schemas to see if the tools can update, but putting this out here to get some visibility and possible direction.

> Preview feature "atomicNumberOperations" is deprecated. The functionality can be used without specifying it as a preview feature.

Should there be a migration schema that removes this preview feature?

### CODE REVIEW

**Comment by paazmaya** [comment]
How is the type
`    data: Prisma.ProjectIdNameBrowserDeviceOsViewportCustomTagsBranchNameCompoundUniqueInput`
at https://github.com/Visual-Regression-Tracker/backend/blob/7a47481c777006ccca25b770d3c7f106410fd6b9/src/test-variations/test-variations.service.ts#L45
generated?
Or what magic is this?

**Comment by paazmaya** [comment]
I cannot get past `npx prisma migrate dev`, as it mentions:

> Error: The migrations folder contains migration files from an older version of Prisma Migrate which is not compatible.
> Read more about how to upgrade to the new version of Migrate:
> https://pris.ly/d/migrate-upgrade

But the root cause is not found...

**Comment by pashidlos** [comment]
@paazmaya those types are generated from schema file 
starting from Prisma v3 they completely changed that process and to migrate it require redo all DB schema from scratch

**Comment by paazmaya** [comment]
@pashidlos do you mean removing everything under `prisma/migrations` folder?

I am looking to continue by upgrading to Prisma v4, and it might be easier without the legacy migration files...

**Comment by paazmaya** [comment]
Continuing in #206

**Pull request closed without merging**
