### PR TITLE
Upgrade Docker images to use LTS version of Node.js #184

### PR DESCRIPTION
**Pull request by paazmaya**
Replacement for #203, while fixing #184

### CODE REVIEW

**Comment by monotek** [comment]
imho using a floating tag for a container is not a good idea, in terms of (automatic) updates an reproducablity.

**Comment by pashidlos** [comment]
> imho using a floating tag for a container is not a good idea, in terms of (automatic) updates and reproducablity.

that actually revealed few issues that should be fixed within https://github.com/Visual-Regression-Tracker/backend/pull/211/files 
with specific version tag

**Comment by pashidlos** [comment]
> Looks like it should be Ubuntu 20.04...
> 
> How about that monorepo approach? [Visual-Regression-Tracker/Visual-Regression-Tracker#367](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/367) It would help in keeping versions consistent, now that I tried to do it in all typescript repos, but this issue came up.

I don't mind as long as it keeps working

**Comment by monotek** [comment]
> Ubuntu 20.04

typo?

Current LTS release would be Ubuntu 22.04

**Comment by paazmaya** [comment]
Since the latest, 22.04, was failing, should use 20.04

**Pull request merged**
